zoom in: edit.zoom_in()
zoom out: edit.zoom_out()
zoom reset: edit.zoom_reset()
scroll up: edit.page_up()
scroll down: edit.page_down()
copy that: edit.copy()
cut that: edit.cut()
paste that: edit.paste()
nope: edit.undo()
redo it: edit.redo()
paste match: edit.paste_match_style()
disk: edit.save()
wipe: key(backspace)    
padding: 
	insert("  ") 
	key(left)
slap: edit.line_insert_down()
