lane <number_small>: user.desktop(number_small)
lane next: user.desktop_next()
lane last: user.desktop_last()
lane show: user.desktop_show()
window move lane <number>: user.window_move_desktop(number)
window move lane left: user.window_move_desktop_left()
window move lane right: user.window_move_desktop_right()
